### ISSUE TITLE
Unable to install UnityAd plugin

### ISSUE THREAD

**Issue by vintage** [Heyzap/heyzap-cordova-extras#7]
Shouldn't it use `Fyber_UnityAds_2.0.2-r2.framework`?

https://github.com/Heyzap/heyzap-cordova-extras/blob/b9fb3ac47ae3cc8e894579860fbee1da7f3efa3b/heyzap-cordova-unityads/plugin.xml#L24

```
Error during processing of action! Attempting to revert...
Failed to install 'heyzap-cordova-unityads':CordovaError: Uh oh!
Cannot find framework "/Users/krykowski/workspace/party_game/plugins/heyzap-cordova-unityads/src/ios/Fyber_UnityAds_2.0.2-r1.framework" for plugin heyzap-cordova-unityads in iOS platform
    at handlers.framework.install (/Users/krykowski/workspace/party_game/platforms/ios/cordova/lib/plugman/pluginHandlers.js:86:48)
    at Object.ActionStack.process (/Users/krykowski/workspace/party_game/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/krykowski/workspace/party_game/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/Users/krykowski/workspace/party_game/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at Api.addPlugin (/Users/krykowski/workspace/party_game/platforms/ios/cordova/Api.js:235:10)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:611:6)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:407:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
Error: Uh oh!
Cannot find framework "/Users/krykowski/workspace/party_game/plugins/heyzap-cordova-unityads/src/ios/Fyber_UnityAds_2.0.2-r1.framework" for plugin heyzap-cordova-unityads in iOS platform
```

**Comment by rafaellop** [comment]
I can confirm that for android also it is not possible to install the plugin for UnityAds.
